import {
  Body,
  Container,
  Head,
  Hr,
  Html,
  Text,
  Preview,
  Img,
} from "@react-email/components";
import * as React from "react";

// Base URL, if using Vercel
// const baseUrl = process.env.VERCEL_URL
//   ? `https://${process.env.VERCEL_URL}`
//   : "";

//
const ContactFormEmail = ({ name, email, phone, message }) => (
  <Html>
    <Head />
    <Preview>New Contact Form Submission from {name}</Preview>
    <Body style={main}>
      <Container style={container}>
        {/* image logo */}
        <Img src="/images/logo.png" style={logo} alt="logo" />
        <Text style={heading}>New Contact Form Submission</Text>
        <Hr style={hr} />

        <Text style={paragraph}>
          <strong>Name:</strong> {name}
        </Text>
        <Text style={paragraph}>
          <strong>Email:</strong> {email}
        </Text>
        <Text style={paragraph}>
          <strong>Phone:</strong> {phone}
        </Text>
        <Text style={paragraph}>
          <strong>Message:</strong> {message}
        </Text>

        <Hr style={hr} />
        <Text style={footer}>
          This email was generated by the contact form on your website. Please
          reply directly to {email} to respond to this inquiry.
        </Text>
      </Container>
    </Body>
  </Html>
);

export default ContactFormEmail;

const main = {
  backgroundColor: "#f1ede7",
  fontFamily:
    '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif',
  paddingTop: `32px`,
  paddingBottom: `32px` /* 2rem = 32px */,
  paddingLeft: `24px` /* 1.5rem = 24px */,
  paddingRight: `24px` /* 1.5rem = 24px */,
  maxWidth: `672px` /* 42rem = 672px */,
  marginInline:
    "auto" /* auto margins are often not supported in email clients */,
  border: "1px solid black",
};

const container = {
  // margin: "0 auto",
  padding: "24px 0 32px",
};

const heading = {
  fontSize: "20px",
  fontWeight: "bold",
};

const paragraph = {
  fontSize: "16px",
  lineHeight: "26px",
};
const logo = {
  width: "320px",
  heigh: "160px",
  margin: "0 auto",
};

const btnContainer = {
  textAlign: "center",
};

const button = {
  backgroundColor: "#5F51E8",
  borderRadius: "3px",
  color: "#fff",
  fontSize: "16px",
  textDecoration: "none",
  textAlign: "center",
  display: "block",
  padding: "12px",
};

const hr = {
  borderColor: "#cccccc",
  margin: "20px 0",
};

const footer = {
  color: "#8898aa",
  fontSize: "12px",
};
